### ISSUE TITLE
Security review of ed25519-dalek in relation to rPGP/Delta chat usage?

### ISSUE THREAD

**Issue by hpk42** [dalek-cryptography/ed25519-dalek#100]
Over at https://github.com/deltachat/deltachat-core-rust we are using https://github.com/rpgp/rpgp, a full-Rust OpenPGP implementation which recently got an independent security review on its core code and the RSA implementation.  Both rPGP and RSA were authored by @dignifiedquire. For a second security review we are thinking of also including (parts of?) ed25519-dalek -- the review is going to happen during Dec2019/Jan2020 likely. 

Have there been security reviews already for ed25519-dalek? What would you recommend to get reviewed, or what would be priorities? Anyone here interested in participating in the security review process?

**Comment by isislovecruft** [comment]
Hi! We were reviewed briefly [by Quarkslab](https://blog.quarkslab.com/security-audit-of-dalek-libraries.html) and previously by NCC (audit summary remains private). We believe it to be unlikely for there to be issues at this point in this library. Rather, we would suggest auditing the lower-level `curve25519-dalek` library, particularly the scalar and field backends, as being of greater importance. However, we'd never say no to additional audits (of any of our code), and we're happy to work with auditors to answer questions.

**Comment by isislovecruft** [comment]
Hi again! Feel free to ping me if you need/want any help conducting an audit on any of our code, and please let me know if you have any questions about anything. I'm going to close this for now, if that's okay?

**Comment by hpk42** [comment]
On Wed, Dec 11, 2019 at 14:58 -0800, isis agora lovecruft wrote:

> Hi again! Feel free to ping me if you need/want any help conducting an audit on any of our code, and please let me know if you have any questions about anything. I'm going to close this for now, if that's okay?

sure, thanks! And sorry for not getting back on this myself. 

Scoping for the next review is still ongoing but it's unlikely 
it will include any ECC parts. We are aiming for a third round
to include our then ecc-based stack reviewed (currently still RSA
is our default).
