### ISSUE TITLE
0.9.1 fails to build

### ISSUE THREAD

**Issue by nic-hartley** [dalek-cryptography/ed25519-dalek#109]
```
error[E0432]: unresolved import `rand::thread_rng`
   --> /home/nxh/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-0.9.1/src/ed25519.rs:974:9
    |
974 |     use rand::thread_rng;
    |         ^^^^^^^^^^^^^^^^ no `thread_rng` in the root

error: aborting due to previous error
```

This seems to have been fixed in `master`; could a fix be backported? If not, what's the ETA for 1.0?

I tried using version 1 as recommended in the current README, but that isn't on crates.io yet.

**Comment by tarcieri** [comment]
@nic-hartley you probably want to use https://crates.io/crates/ed25519-dalek/1.0.0-pre.3
