### ISSUE TITLE
unresolved import `rand::thread_rng`

### ISSUE THREAD

**Issue by vi** [dalek-cryptography/ed25519-dalek#113]
```
error[E0432]: unresolved import `rand::thread_rng`
   --> /home/vi/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-0.9.1/src/ed25519.rs:974:9
    |
974 |     use rand::thread_rng;
    |         ^^^^^^^^^^^^^^^^ no `thread_rng` in the root
```

Maybe more `rand` features needs to be included?

Can this crate be used with a custom random generator?

**Comment by vi** [comment]
Maybe `rand` version is not constrained enough? Using `rand 0.6` instead of `rand 0.7` makes error disappear.

**Comment by thedavidmeister** [comment]
can confirm that setting rand to `0.6` worked for me

**Comment by thedavidmeister** [comment]
oh, actually i needed rand `0.7` on latest version of dalek

**Comment by isislovecruft** [comment]
We updated to rand 0.7 recently in all the dalek crates, and this crate is about to have a new 1.0.0-pre.4 release which should fix this issue. Sorry for the confusion!
