### ISSUE TITLE
Document converting between x25519-dalek and ed25519-dalek

### ISSUE THREAD

**Issue by nic-hartley** [dalek-cryptography/ed25519-dalek#118]
I'm using ed25519-dalek for keygen, signing, and verification, and x25519 for ECDH. How do I convert secret public keys between them?

Take this naive attempt -- it seems like this works fine:

```rust
extern crate ed25519_dalek;
extern crate x25519_dalek;
extern crate rand;

use rand::prelude::*;

fn main() {
    let edkey1 = ed25519_dalek::Keypair::generate(&mut thread_rng()).public;
    let xkey = x25519_dalek::PublicKey::from(edkey1.to_bytes());
    let edkey2 = ed25519_dalek::PublicKey::from_bytes(xkey.as_bytes());

    println!("ek1: {:?}", edkey1);
    println!("xk:  {:?}", xkey);
    println!("ek2: {:?}", edkey2);
    
    assert_eq!(Ok(edkey1), edkey2);
}
```

Right up until you try to use the keys, and then you realize that you've actually got two _different_ public keys. This makes sense: They use a different internal representation. But that doesn't help me figure out how to convert between them, which I'd very much like to do.

Similarly, how do you convert between secret keys? Does byte-copying work there, or do I need to do something special?

**Comment by nic-hartley** [comment]
I'm fairly sure this is going to involve going through `curve-25519`, but I'd like confirmation (and, ideally, someone else to write that code for me, so I don't have to...)

**Comment by burdges** [comment]
You can use [`EdwardsPoint::to_montgomery`](https://doc.dalek.rs/curve25519_dalek/edwards/struct.EdwardsPoint.html#method.to_montgomery) which should agree with agl's https://github.com/agl/ed25519/blob/master/extra25519/extra25519.go#L28  

I think this code should commute with normal secret key generation for both schemes, but maybe check wire format's with agl's go code since folks use that in the wild.
```
pub fn edwards_to_montgomery(cepk: [u8; 32]) -> Option<[u8; 32]> {
    let epk = ::curve25519_dalek::edwards::CompressedEdwardsY(cepk).decompress() ?;
    if epk.is_small_order() { return None; }
    // Or maybe you prefer: if epk.is_identity() { return EdwardsPoint::identity(); } 
    epk.to_montgomery().to_bytes()
    // Or return the curve25519_dalek::MontgomeryPoint if you prefer.
}
```
There exists a more complex scheme called XEd25519 for folks who only deploy X25519 first and later wish to add Ed25519 signatures. 

Warning:  There are always risks in using the same secret key for more protocols, so you kinda need to understand more when doing so.

**Comment by nic-hartley** [comment]
@burdges Currently I keep an Ed255519 key and (try to) derive the X25519 key when I need to do key agreement to encrypt data, and using the Ed25519 keys to sign/verify data. I could instead generate/store two keys, one for Ed25519 and one for X25519.

What kinds of risks are there with using one secret key?

**Comment by burdges** [comment]
It depends what other protocols you users use with those keys.  Anything strange?  Account keys for blockchains tends to qualify as strange since many niche wallet protocols exist.

**Comment by nic-hartley** [comment]
Nothing that I'd call strange, but as you can probably tell, I'm new to crypto. I've got a longer, probably bad description [here](https://github.com/nic-hartley/mesher/blob/master/README.md#Crypto), but in brief, I need asymmetric crypto. I'm doing that by:

- Generating a random keypair
- Doing DH between the random secret key and the target's public key
- Encrypting the message with AES-256-GCM
- Sending the random public key with the message

Then to decrypt, the inverse -- DH, decrypt.

So... up to you if that's strange. AFAIK it's a pretty standard construction, since it should be what TLS does, but with specific primitives instead of doing any negotiation. 

No blockchain stuff, no. Although I _could_ get VC funding if I threw some in there... ;)

**Comment by burdges** [comment]
It's probably fine if you pass the key exchange result into the AEAD without leaking it anywhere.

**Comment by nic-hartley** [comment]
Yup, that's what I'm doing.

Actually, in the mean time, I went ahead and implemented a system with two side-by-side keys -- it proved to be easier than trying to wrap my head around Ed/X 25519 so I could make sure keys were getting converted appropriately, and it still supports all the operations I needed. Thanks for that suggestion.

I'm not sure if I should close this issue, tbh. I'd still like to see it officially documented somewhere how to convert keys, since not everyone will have my luxury of being able to simply redefine the protocol.

**Comment by burdges** [comment]
If you use the same secret key then you might as well convert btw.

**Comment by isislovecruft** [comment]
Hi @nic-hartley! (And thanks for answering @burges!)

Currently, we only support a unidirectional isogeny from Twisted Edwards form (ed25519, i.e. signing/verifying) to Mongomery form (x25519, i.e. ECDH). One reason why we don't support the inverse operation is that it requires storing an extra sign bit relating to the original group element in Twisted Edwards form, after converting to Montgomery, sign the latter uses (in affine coordinates) an x-coordinate-only representation. So it's not exactly user-friendly or intuitive, and easy to mess up. The other reason is that, while it would be possible to implement this, we have a sort of political opinion that using the same keypair for multiple protocols is bad practice and should be avoided at all costs. But that said, and as said above, the one-way isogeny can be used with `EdwardsPoint::to_montgomery()`, which will give you the innards of an `x25519::SecretKey`.
