### ISSUE TITLE
Accept generic Digest

### ISSUE THREAD

**Issue by mgjm** [dalek-cryptography/ed25519-dalek#121]
As explained in [#69 (comment)](https://github.com/dalek-cryptography/ed25519-dalek/issues/69#issuecomment-482871703):

> Ed25519 is a concrete instantiation of the EdDSA signature framework, which is generic over both an Edwards curve and a hash function (H). Ed25519 instantiates EdDSA with the “edwards25519” (RFC8032 terminology) elliptic curve and SHA-512.

But for some projects it would be useful to instantiates EdDSA with curve25519 and `Blake2b`.

Therefore I would suggest to split the `ed25519-dalek` crate into two crates:
- `eddsa-dalek`: Generic in terms of the `Digest` implementation
- `ed25519-dalek`: Hardcoded `sha2::Sha512` digest

I set up a test workspace with these two separate crates:
[mgjm/split-ed25519-dalek](https://github.com/mgjm/split-ed25519-dalek)

The `ed25519-dalek` crate only needs to reexport all non generic types and functions and export type aliases with hardcoded `Sha512` digest:
[`ed25519-dalek/src/lib.rs`](https://github.com/mgjm/split-ed25519-dalek/blob/32f756e/ed25519-dalek/src/lib.rs#L254-L264)

All tests and benchmarks using the `ed25519-dalek` crate still work without any modification.

---

This issue is also related to #75 and #79.

**Comment by isislovecruft** [comment]
After internal discussion on the dalek team we decided that 1) the API complications combined with 2) making it easier for people to do EdDSA signatures in a non-spec-compliant manner meant we were not going to continue to support generic digests.
