### ISSUE TITLE
Release with zeroize

### ISSUE THREAD

**Issue by dignifiedquire** [dalek-cryptography/ed25519-dalek#122]
The switch to zeroize was already made on the development branch. Any chance you could release an updated version of the pre-release, that includes that change, tank you.

**Comment by garious** [comment]
Hey @isislovecruft, transaction signing from the browser with ed25519-dalek would be super cool. I'd use it for sure. Got plans for a new release any time soon?

**Comment by isislovecruft** [comment]
@garious I'm about to do a 1.0.0-pre.4 release (with probably one or two more prereleases before actually stabilising, sorry sorry).
