### ISSUE TITLE
Field51 Benchmarks?

### ISSUE THREAD

**Issue by jon-chuang** [dalek-cryptography/ed25519-dalek#125]
Are there field51 benchmarks? In an implementation of Field51 generated by a generic pseudo-mersenne prime field macro in pure rust, I am getting about 25ns per squaring and 35ns per mul.

**Comment by isislovecruft** [comment]
I think you're looking for the [curve25519-dalek repo](https://github.com/dalek-cryptography/curve25519-dalek).
