### ISSUE TITLE
Question about PublicKey 

### ISSUE THREAD

**Issue by Fiono11** [dalek-cryptography/ed25519-dalek#128]
Why is PublicKey a tuple of a CompressedEdwardsY and an EdwardsPoint? Shouldn't it be just one?

**Comment by Fiono11** [comment]
From what I understand CompressedEdwardsY is the EdwardsPoint compressed, but why representing the PublicKey with both?

**Comment by WildCryptoFox** [comment]
The `CompressedEdwardsY` is present as a cache, as compressing has a cost and the result is frequently used. If you don't use it, the optimizer is trusted to remove it.

**Comment by Fiono11** [comment]
Makes sense. Thank you!
