### ISSUE TITLE
Why doesn't this work?

### ISSUE THREAD

**Issue by Fiono11** [dalek-cryptography/ed25519-dalek#129]
Can anyone tell me why this doesn't work, please?
```
use ed25519_dalek::*;
use curve25519_dalek::edwards::*;
use rand::rngs::OsRng;

fn main() {
    let mut rng = OsRng;
    let sk = Scalar::random(&mut rng);
    let pk = sk*ED25519_BASEPOINT_POINT;
    let s = SecretKey::from_bytes(&sk.to_bytes()).unwrap();
    let p1: PublicKey = (&s).into();
    let p2: PublicKey = PublicKey::from_bytes(&pk.compress().to_bytes()).unwrap();  
    assert_eq!(p1, p2);
}
```

**Comment by WildCryptoFox** [comment]
`SecretKey::from_bytes` doesn't work how you think it works.

The `bytes` are the seed, not the scalar, which are expanded by SHA512 to the scalar and key used for deterministic nonce derivation. See [`From<&'_ SecretKey> for ExpandedSecretKey`](https://docs.rs/ed25519-dalek/1.0.0-pre.3/src/ed25519_dalek/secret.rs.html#267).

**Comment by Fiono11** [comment]
Thank you!
