### ISSUE TITLE
errors module is private

### ISSUE THREAD

**Issue by benxgao** [dalek-cryptography/ed25519-dalek#132]
By given
```rs
...
fn sign_ed25519(secret_key) -> Result<Signature, SignatureError> {...}
...

# [test]
...
assert_eq!(
  instance.sign_ed25519(&secret_key), Err(SIGNATURE_ERROR)
);
...
```
Tried several ways on dealing with `SIGNATURE_ERROR` in above code scenario:
1. `Err(ed25519_dalek::SignatureError)` is not visible due to private fields;
2. `Err(ed25519_dalek::errors::InternalError)` seems private as well;

Any workaround/suggestions on handling errors right now? 
Will `mod errors` be public in future, so that `InternalError` enums may be used?

**Comment by WildCryptoFox** [comment]
Try `instance.sign_ed25519(&secret_key).is_err()`. Generally speaking you'll want to avoid matching against error types because they can cause leakages. You may print the errors to stderr to observe details for debugging.

**Comment by isislovecruft** [comment]
Thanks @benxgao and @WildCryptoFox. Hope that answered your issue, but feel free to reopen if not.
