### ISSUE TITLE
buid error found

### ISSUE THREAD

**Issue by elderbig** [dalek-cryptography/ed25519-dalek#136]
git clone --depth 1 https://github.com/dalek-cryptography/ed25519-dalek.git
cd ed25519-dalek
cargo build

Updating `git://mirrors.ustc.edu.cn/crates.io-index` index
    Updating git repository `https://github.com/isislovecruft/merlin`
error: failed to select a version for the requirement `merlin = "^1"`
candidate versions found which didn't match: 2.0.0
location searched: Git repository https://github.com/isislovecruft/merlin?branch=develop
required by package `ed25519-dalek v1.0.0-pre.3 (/home/sh/temp/ed25519-dalek)`

**Comment by isislovecruft** [comment]
This was due to @hdevalence yanking old crate versions. The stable release version of ed25519-dalek uses merlin 2.0.
