### ISSUE TITLE
benchmark failed

### ISSUE THREAD

**Issue by triplewz** [dalek-cryptography/ed25519-dalek#158]
Hello, I have run the test cases and it worked fine, but the benchmark test failed.

```
error[E0432]: unresolved import `ed25519_dalek::verify_batch`
  --> benches/ed25519_benchmarks.rs:24:9
   |
24 |     use ed25519_dalek::verify_batch;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `verify_batch` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `ed25519-dalek`
```

**Comment by AnomalRoil** [comment]
It's probably because you need to use the `batch` feature.
https://github.com/dalek-cryptography/ed25519-dalek/blob/925eb9ea56192053c9eb93b9d30d1b9419eee128/Cargo.toml#L48

**Comment by isislovecruft** [comment]
Yes, when running the benchmarks the "batch" feature must be enabled. There is some sort of bad interaction between cargo and criterion causing the issue with the feature not being auto-enabled when running `cargo bench`.
