### ISSUE TITLE
Failing to build "no_std" application.

### ISSUE THREAD

**Issue by cpfister** [dalek-cryptography/ed25519-dalek#163]
Hi,

I'm trying to use signature verification in embedded firmware. What I have is basically a "no_std" main package ('nrf52840_dk_main') configured for building with the 'thumbv7em-none-eabihf' target. It imports another package X, which is a "no_std" library. This build, deploys and runs just fine on the embedded system.

Then I add the following line to X's Cargo.toml:

**ed25519-dalek = "1.0.1"**

But now, 'nrf52840_dk_main' doesn't build anymore:

<img width="737" alt="Screenshot 2021-03-02 at 21 11 54" src="https://user-images.githubusercontent.com/1516153/110007769-5050e580-7d1b-11eb-8ff3-91296165d4c1.png">

It seems like somewhere, someone is requiring 'std', but I have no idea where to look and how to fix that.
And yes, I definitely have installed 'thumbv7em-none-eabihf'.

I haven't found documentation about any features that I would have to configure differently for ed25519-dalek, but maybe I just missed it. I have tried to use the 'default-features = false' that is needed for some other crypto crates, but this made it even worse.

Does anyone have an idea what I'm doing wrong here?

**Comment by tarcieri** [comment]
> Then I add the following line to X's Cargo.toml:
>
> ed25519-dalek = "1.0.1"

`std` is a default feature: https://github.com/dalek-cryptography/ed25519-dalek/blob/master/Cargo.toml#L52

You need to use:

```toml
ed25519-dalek = { version = "1", default-features = false, features = ["u32_backend"] }
```

**Comment by cpfister** [comment]
Wow, now **that** was a really quick answer! And it helped; that _u32_backend_ feature made the difference!
Thanks a lot, Tony, much appreciated!
