### ISSUE TITLE
Support deserialising and serialising to/from PKCS8 keypair bytes

### ISSUE THREAD

**Issue by ShadowJonathan** [dalek-cryptography/ed25519-dalek#169]
Is it possible to allow a `to_bytes`/`from_bytes` equivalent for PKCS8? Maybe related to or supported by [`pkcs8`](https://docs.rs/pkcs8/0.6.0/pkcs8/)

**Comment by ShadowJonathan** [comment]
That PR doesn't do it for `PublicKey`, `SecretKey`, or `KeyPair`, which is what I need it for, unless i've missed it.

**Comment by tarcieri** [comment]
The types have slightly different names in `ed25519-zebra`.

For `SecretKey` and `KeyPair` you can look at `ed25519_zebra::SigningKey`:

https://github.com/ZcashFoundation/ed25519-zebra/pull/46/files#diff-94628efec6bef739bbeb2d97cf8c4a09449a09d8998a99db7f95c536a922cbfb

For `PublicKey` you can look at `ed25519_zebra::VerificationKey`:

https://github.com/ZcashFoundation/ed25519-zebra/pull/46/files#diff-7f04c5909ce87b5d301edd2512fe7dd4f5f57917769bafaae2f47813fc0fb135

**Comment by isislovecruft** [comment]
Hi @ShadowJonathan and @tarcieri!

I'm not super interested in maintaining PEM/DER serialisation formats in this crate, but nothing is stopping anyone from implementing that on their wrapper key types externally to `ed25519-dalek`. (Thanks @tarcieri for the pointers to how this is done and an external PKCS8 Rust implementation!)

If a lot of people complain at this lack of functionality in the future, I might consider adding it, but again frankly it's something I'd rather not maintain as I'm already completely swamped in maintenance tasks.

**Comment by tarcieri** [comment]
FYI: the latest version of the `ed25519` crate has native PKCS#8 support:

https://docs.rs/ed25519/1.3.0/ed25519/pkcs8/struct.KeypairBytes.html

It would be nice to add some `From`/`TryFrom` conversions between `ed25519::KeypairBytes` <=> `ed25519_dalek::Keypair`
