### ISSUE TITLE
Function to create private key from seed

### ISSUE THREAD

**Issue by mschneiderwng** [dalek-cryptography/ed25519-dalek#17]
Is there a safe way to deterministically create a private key from a seed?

**Comment by calidion** [comment]
why it is closed?
Is there a way to generate private key with seed?

**Comment by tarcieri** [comment]
https://docs.rs/ed25519-dalek/1.0.0-pre.1/ed25519_dalek/struct.SecretKey.html#method.from_bytes

**Comment by calidion** [comment]
@tarcieri  Thanks.
