### ISSUE TITLE
Expose `InternalError`

### ISSUE THREAD

**Issue by ShadowJonathan** [dalek-cryptography/ed25519-dalek#174]
While working on a programmatic `if let` switcher to allow developers to find out exactly what error occured in their program, i found out that `ed25519-dalek` has `pub(crate)` on `InternalError`.

I'd like to switch on them with `if let`, so that a `VerifyError` is different than a `PointDecompressionError` error in my program, and where i could change behaviour depending on both (think `403` http error on the first, but `400` http error on the last)

**Comment by isislovecruft** [comment]
Unfortunately the `InternalError` type was written to be internal to the library, as its error `Display` messages, and even the names of the variants in the enum, were not written to be user-friendly or understandable.

**Comment by ShadowJonathan** [comment]
This is exactly why i wrote this issue, though, as it looked like that for me.

Still, the original request hasn't been unanswered; allow programmers to match the error and figure out exactly what is going on, for more programmatic error checking. Please re-open this issue, as that functionality would be quite useful.

**Comment by tarcieri** [comment]
Generally I think it's a cryptographic best practice not to directly expose this sort of detailed error information. Many Rust cryptography crates use opaque error types.

There is a history of such information being observable by attackers, and leveraged for attacks.

**Comment by ShadowJonathan** [comment]
Ah, hmm, good point
