### ISSUE TITLE
Update to 2018 edition

### ISSUE THREAD

**Issue by gbaranski** [dalek-cryptography/ed25519-dalek#181]
Hi, code still uses old Rust 2015, it'd be great to migrate it to 2018 or upcoming 2021 edition. I made some work on this on my fork, https://github.com/gbaranski/ed25519-dalek/blob/master/src/lib.rs.

**Comment by laundry-96** [comment]
Any help needed with this? I'm interested in a 2018 version as well.

**Comment by gbaranski** [comment]
> Any help needed with this? I'm interested in a 2018 version as well.

I can handle this, but at the moment I don't know if my PR would be accepted.

cc @isislovecruft

**Comment by tarcieri** [comment]
Edition was bumped to 2021 in #218
