### ISSUE TITLE
PublicKey should derive Hash

### ISSUE THREAD

**Issue by inetic** [dalek-cryptography/ed25519-dalek#183]
Re-opening the issue #120 as it hasn't been solved yet.

The original author @dvc94ch [seems to open and close issues because it fits his workflow](https://github.com/dalek-cryptography/ed25519-dalek/issues/162#issuecomment-938157591).

The original text:

@dvc94ch wrote

> Unless there's a cryptographic reason why it should not derive Hash, it would be a good idea.

@burdges wrote

> It should define Hash with .0.as_bytes() not #[derive(Hash)] since the serialized form already exists, and because points in protective coordinates require normalization. Aside from the obvious reasons: [Projective Coordinates Leak](https://www.researchgate.net/publication/221348015_Projective_Coordinates_Leak)

There is currently a PR for this https://github.com/dalek-cryptography/ed25519-dalek/pull/176. Likely motivated by @burdges' comment [here](https://github.com/dalek-cryptography/ed25519-dalek/issues/52#issuecomment-602239815). The CI on that PR is currently failing, but it doesn't seem like the failure is caused by the PR changes.

Could someone please re-run the CI?

**Comment by dvc94ch** [comment]
looks like I may have closed it accidentally

**Comment by mimoo** [comment]
wondering about this as well

**Comment by rozbb** [comment]
Resolved in https://github.com/dalek-cryptography/ed25519-dalek/pull/265
