### ISSUE TITLE
verify_strict_prehashed

### ISSUE THREAD

**Issue by prismatic-obloquy** [dalek-cryptography/ed25519-dalek#185]
ed25519-dalek has `PublicKey::verify_strict` and `PublicKey::verify_prehashed`, but it's [not clear](https://docs.rs/ed25519-dalek/1.0.1/ed25519_dalek/struct.PublicKey.html#method.verify_prehashed) if the prehashed check is strict and if not how to get a strict prehashed check. Not being a cryptographer I can't say for sure but I think this should be possible?

**Comment by rozbb** [comment]
Resolved in https://github.com/dalek-cryptography/ed25519-dalek/pull/212
