### ISSUE TITLE
Implement `Signer` for `SecretKey`

### ISSUE THREAD

**Issue by malte-v** [dalek-cryptography/ed25519-dalek#187]
I'd like to sign messages with a `SecretKey`, but apparently I need an `ExpandedSecretKey` to sign anything. It's rather annoying to perform this conversion each time something needs to be signed. Since `Keypair` already converts its `SecretKey` to an `ExpandedSecretKey` when `sign()` is called on it, why not implement this functionality for `SecretKey` as well?

**Comment by malte-v** [comment]
Oops, I overlooked that `ExpandedSecretKey::sign` also takes the public key (why?). Then it probably wouldn't be so smart to derive the public key every time something is signed.

**Comment by tarcieri** [comment]
> I overlooked that ExpandedSecretKey::sign also takes the public key (why?)

The Ed25519 signature algorithm commits to the public key of the signer as a domain separation parameter when computing a message digest.

**Comment by malte-v** [comment]
Slightly off-topic, but how does hashing in the public key provide any kind of domain separation? Currently I'm using `sign_prehashed` and put a different string constant into the hash for each type of data I'm signing, if that is what you mean by "domain separation".

**Comment by tarcieri** [comment]
It ensures signatures made under a specific public key will never verify under another public key, by committing to the key in advance as part of the Fiat-Shamir "challenge".

**Comment by malte-v** [comment]
> by committing to the key in advance as part of the Fiat-Shamir "challenge".

Okay, this is way over my head, but thanks for answer :)

**Comment by burdges** [comment]
Although more careful protocols avoid this, there exist schemes like soft key derivations (BIP32, HDKD, etc.) that created multiple secret keys with known algebraic relationships, so a vanilla schnorr signatures under one key could easily be transformed into a signature by a related key.  Ed25519 fixes this by hashing the public key.

As an interesting aside, BLS has exactly the same problem, but the fix breaks everything good about BLS, meaning BLS can only be used where key management can forbid related keys.
