### ISSUE TITLE
Keypair should be named KeyPair?

### ISSUE THREAD

**Issue by sjud** [dalek-cryptography/ed25519-dalek#191]
May I submit a pull request changing Keypair to KeyPair?

**Comment by tarcieri** [comment]
FWIW the [`ed25519` crate also uses `Keypair`](https://docs.rs/ed25519/1.3.0/ed25519/pkcs8/struct.KeypairBytes.html)

**Comment by rozbb** [comment]
As of #242 it's called `SigningKey`
