### ISSUE TITLE
`ed25519` v1.4.0 has an MSRV of 1.56

### ISSUE THREAD

**Issue by tarcieri** [dalek-cryptography/ed25519-dalek#194]
This issue is mostly a heads up that the latest `ed25519` crate release, v1.4.0, has bumped its minimum supported Rust version to 1.56, as part of a Rust 2021 edition upgrade:

https://github.com/RustCrypto/signatures/pull/450

This may manifest in a Cargo resolution failure that looks like the following when building `ed25519-dalek` on earlier versions of Rust:

```
error: failed to parse manifest at `.cargo/registry/src/github.com-1ecc629/ed25519-1.4.0/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

If you are using `ed25519-dalek` with versions of Rust prior to 1.56, you will need to add a constraint to your Cargo.toml such as the following:

```toml
[dependencies]
ed25519 = ">=1, <1.4" # ed25519 1.4 requires MSRV 1.56
```

It might be worth adding such a constraint to `ed25519-dalek` itself, although this does have the downside of rejecting compatible versions of crates on newer MSRVs.

**Comment by assafmo** [comment]
Thank you @tonychain, I can confirm that this solved this issue for me too.
