### ISSUE TITLE
Compatibility with ecies-ed25519

### ISSUE THREAD

**Issue by mattnappo** [dalek-cryptography/ed25519-dalek#208]
Of course, ed25519-dalek does not implement encryption/decryption. However, [ecies_ed25519](https://docs.rs/ecies-ed25519/latest/ecies_ed25519/) does support encryption/decryption, but not signatures or validation. So, if I want to use the same keypair for both encryption/decryption and digital signature validation, I would imagine using both crates. However, I am not sure if ed25519_dalek is cross-compatible with ecies_25519. If not, would it be valuable to make them interoperable?

**Comment by rozbb** [comment]
This is not an intended use case of ed25519-dalek. For a standards-compliant ECIES library, see [hpke](https://github.com/rozbb/rust-hpke)
