### ISSUE TITLE
Bench issue

### ISSUE THREAD

**Issue by LumaRay** [dalek-cryptography/ed25519-dalek#215]
Hi!
I get this error while performing cargo bench:

Compiling criterion v0.3.6
error[E0432]: unresolved import `ed25519_dalek::verify_batch`
  --> benches/ed25519_benchmarks.rs:24:9
   |
24 |     use ed25519_dalek::verify_batch;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `verify_batch` in the root

**Comment by rozbb** [comment]
Fixed in #220
