### ISSUE TITLE
AVX2 bench issue

### ISSUE THREAD

**Issue by LumaRay** [dalek-cryptography/ed25519-dalek#216]
Hi!
While trying to test AVX2, I get this error:

test@ubuntu:~/ed25519-dalek$ cargo bench --features=avx2_backend
error: Package `ed25519-dalek v1.0.1 (/home/test/ed25519-dalek)` does not have the feature `avx2_backend`

**Comment by rozbb** [comment]
The correct feature to use is `simd_backend`. It's documented at the very end of the README. We should probably change the shell commands though because they're quite old
