### ISSUE TITLE
Misuse of some public apis can result to private key exposure.

### ISSUE THREAD

**Issue by shareef-dweikat** [dalek-cryptography/ed25519-dalek#221]
Some security researchers reported that ed25519-dalek library allows a public api where secret and public key can be provided independently as signing function inputs. Misuse of these public apis can result to private key exposure.

Please refer to this link for more info: https://github.com/MystenLabs/ed25519-unsafe-libs

**Comment by tarcieri** [comment]
This was fixed in #205, and will be released in `ed25519-dalek` v2.0
