### ISSUE TITLE
Write unit tests for validation criteria, and write `verify_permissive()`

### ISSUE THREAD

**Issue by rozbb** [dalek-cryptography/ed25519-dalek#229]
Currently our validation criteria are implicit and unique among all the ed25519 implementations. We should:

* Measure how `verify()` performs on the [CCTV test vectors](https://github.com/C2SP/CCTV/blob/main/ed25519vectors/ed25519vectors.json) and turn that into asserts so we can catch validation-breaking changes in CI
* Measure how `verify_strict()` performs on the same test vectors. It should reject every one of them.
* Write and expose a `verify_permissive()` function, and ensure it permits all the standard-abiding test vectors. The reason for a `verify_permissive()` is mostly due to Henry's reasoning in the [validation criteria post](https://hdevalence.ca/blog/2020-10-04-its-25519am): it is really weird to have individual signature verification to differ from batch verification. It's also useful for consensus purposes, which is why `ed25519-zebra` exists at all.

**Comment by burdges** [comment]
What is the use case for `verify_strict`?

**Comment by rozbb** [comment]
The comments mention Signal and Tor as users of a nonmalleability property (ie a passive adversary cannot create a fresh signature given an existing signature). I don't know more than that though

**Comment by burdges** [comment]
I donno how nonmalleability comes up in tor or signal, but signal eventually used a VRF somewhere, so maybe signal needed stronger than this.  cc @trevp 

A priori, I'd think this sort of nonmalleability should be done by ``internal_signature.R.mul_by_cofactor()``, which sounds lighter weight conceptually than a validation criteria, so maybe one should ask more widely if this winds up useful?

**Comment by rozbb** [comment]
Closing since first half was resolved by #253. Second half is a dupe of https://github.com/dalek-cryptography/ed25519-dalek/issues/152
