### ISSUE TITLE
Request: Move to rand 0.5.

### ISSUE THREAD

**Issue by 0ndorio** [dalek-cryptography/ed25519-dalek#23]
The release of `rand 0.5` brought some major changes and it would be great to have an ed2519-dalek release which is compatible with these changes.

The current master branch still depends on `v.04` but the development branch already got an update to to a pre-release of `v0.5`.  Is there any additional work required to move this to the actual release version and merge that changes into master?

**Comment by tarcieri** [comment]
Opened a PR For this: #26

**Comment by 0ndorio** [comment]
thx :)

**Comment by isislovecruft** [comment]
This is done and it'll be in the next version! I'll release a 0.7.0 maybe tonight or tomorrow.
