### ISSUE TITLE
Reduce proliferation of nondefault features

### ISSUE THREAD

**Issue by rozbb** [dalek-cryptography/ed25519-dalek#234]
Some features are accidentally activated transitively. For example, `alloc -> rand/alloc`, which activates the `rand` feature. This is a problem if we want to provide semver guarantees for default-on features.

Relatedly, `cargo test --no-default-features` fails on `release/2.0` currently because a lot of our tests use `generate()` which requires `rand` (or, consequently, `alloc, `std`,`batch`, or `batch_deterministic`). I think a `mock.rs` module would be useful here, but we have a lot of doctests that would be affected and it'd look nasty. Maybe worth it regardless though.

**Comment by tarcieri** [comment]
Opened #235 to utilize namespaced/weak features

**Comment by rozbb** [comment]
Resolved by #235
