### ISSUE TITLE
Update sha2 to 0.10

### ISSUE THREAD

**Issue by benma** [dalek-cryptography/ed25519-dalek#238]
It causes a duplicate dep in my project (0.10 and 0.9).

https://github.com/dalek-cryptography/ed25519-dalek/blob/7529d65506147b6cb24ca6d8f4fc062cac33b395/Cargo.toml#L32

**Comment by pinkforest** [comment]
It's in the release/2.0 branch

**Comment by benma** [comment]
When is soon?

Maybe you could make an intermediate `1.X` release to bump sha2to 0.10? It is still blocking me from updating other deps that depend on sha2 0.10.

**Comment by tarcieri** [comment]
@benma is there a specific reason you can’t use a prerelease?

**Comment by benma** [comment]
@tarcieri I prefer to use official releases. I assume prereleases are for testing and may contain bugs.

**Comment by tarcieri** [comment]
We’re currently on release candidates. They are safe to use

**Comment by benma** [comment]
Okay, thanks for the info!
