### ISSUE TITLE
u128 has been stabilized and no longer needs feature gating

### ISSUE THREAD

**Issue by Shnatsel** [dalek-cryptography/ed25519-dalek#24]
u128 has been [stabilized](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1260-2018-05-10) in Rust 1.26. The feature that enables in ed25519-dalek can now be enabled by default.

It might be a good idea to make it possible to turn off the feature so that people can still build this library on older compilers. Or it might not, to cut down on amount of code to audit.

**Comment by isislovecruft** [comment]
Thanks! As of a4be92b it's enabled by default. You can change to not using it with the `u32_backend` feature.
