### ISSUE TITLE
Release 2.0 TODO

### ISSUE THREAD

**Issue by pinkforest** [dalek-cryptography/ed25519-dalek#245]
**Batching**
- https://github.com/dalek-cryptography/ed25519-dalek/pull/220
- https://github.com/dalek-cryptography/ed25519-dalek/pull/256
- ^ addresses: https://github.com/dalek-cryptography/ed25519-dalek/issues/228

**Perf-on-Default**
- https://github.com/dalek-cryptography/ed25519-dalek/pull/251

**Documentation**
- https://github.com/dalek-cryptography/ed25519-dalek/pull/241
- ^ addresses: https://github.com/dalek-cryptography/ed25519-dalek/issues/248
- https://github.com/dalek-cryptography/ed25519-dalek/pull/243

**Testing/Validation**
- https://github.com/dalek-cryptography/ed25519-dalek/pull/253
- addresses: https://github.com/dalek-cryptography/ed25519-dalek/issues/229

**Signing/Verifying API Change**
- https://github.com/dalek-cryptography/ed25519-dalek/pull/230
- https://github.com/dalek-cryptography/ed25519-dalek/pull/247
- https://github.com/dalek-cryptography/ed25519-dalek/pull/252

**Maintenance**
- https://github.com/dalek-cryptography/ed25519-dalek/pull/235
- https://github.com/dalek-cryptography/ed25519-dalek/pull/246
- https://github.com/dalek-cryptography/ed25519-dalek/pull/244

..

**Comment by tarcieri** [comment]
I need to cut a final release of `ed25519` v2.0.0 as well: https://github.com/RustCrypto/traits/issues/1171

**Comment by Chaostheorie** [comment]
Is there anything stopping a full 2.0.0 release anymore? I recently had problems with the fixed dependency on zeroize `=1.3` in the latest stable with the latest stable for secrecy (`0.8`, depends on `zeroize=^1.8`).

**Comment by pinkforest** [comment]
Use the 2.0.0-rc.2 it should be perfectly usable. There are risks doing a full release without properly tested out first in wild.

**Comment by tarcieri** [comment]
@Chaostheorie there are still breaking changes happening, for example #293.

In the meantime as @pinkforest the RCs should unblock you.

**Comment by Chaostheorie** [comment]
Okay, thank you for the quick response. I'll try to patch it to the release candidate then and look forward to the new stable release.

**Comment by juchiast** [comment]
When can we expect a 2.0 release? This crate has the same zeroize issue of curve25519-dalek 3.0

https://github.com/dalek-cryptography/curve25519-dalek/issues/452 
https://github.com/solana-labs/solana/issues/26688

**Comment by matthiasbeyer** [comment]
crates.io already has the 2.0.0 release, but there is no tag yet. Maybe it was forgotten?

**Comment by rozbb** [comment]
Hi, indeed we've released 2.0! In addition, we moved this repo over to https://github.com/dalek-cryptography/curve25519-dalek, which is why you don't see the tag here. We're in the process of migrating the issues/PRs from here to there.

**Comment by matthiasbeyer** [comment]
Um... this _is_ dalek-cryptography/ed25519, isn't it? Migrating tags is `git push --tags`, right? Am I missing something?

**Comment by rozbb** [comment]
Indeed it is, but we moved all development to the monorepo mentioned above. Tags can be found [there](https://github.com/dalek-cryptography/curve25519-dalek/releases/tag/ed25519-2.0.0)

**Comment by matthiasbeyer** [comment]
Ah, sorry... I mis-read your message to link to this same repo. Everything alright.
