### ISSUE TITLE
From x25519

### ISSUE THREAD

**Issue by aep** [dalek-cryptography/ed25519-dalek#25]
LIt appears to be possible to convert x25519 to ed25519. Is that something 
that makes sense to implement?

https://moderncrypto.org/mail-archive/curves/2014/000293.html

https://download.libsodium.org/doc/advanced/ed25519-curve25519.html

**Comment by isislovecruft** [comment]
It technically *is* [implemented](https://github.com/dalek-cryptography/curve25519-dalek/blob/87a1815/src/montgomery.rs#L110), but it's purposefully not exposed in `ed25519-dalek`. Unless someone's doing something fairly weird, x25519 should generally be used as an ephemeral key exchange.  So there's two use cases:

1. a user wants to sign something with an ephemeral key (which doesn't really make sense?), or
2. a user does x25519 with a static key and wishes to also sign with it (this seems scary, and if someone were committed to doing this they should be going the other direction, i.e. extended twisted Edwards (a.k.a. ed25519) to Montgomery (a.k.a. x25519).

The reasoning for this is that the mapping is not fully defined in the Montgomery→Edwards case, as the sign of the Y-coordinate is lost when doing Edwards→Montgomery. 

That said, I know there *are* use cases for doing this, as much as I don't agree with them and think the practice should be avoided. (Signal, for example, does this.) If you or anyone else has such a use case, I'd be happy to hear about it (and honestly try to convince you to re-engineer your protocol :).

**Comment by aep** [comment]
Thank you for your opinion on this. Sounds like the security of doing the conversion isn't well known.  I did indeed decide to redesign the crypto system instead to use x25519 ephermals signed by ed25519 instead.
