### ISSUE TITLE
Batch verification

### ISSUE THREAD

**Issue by PlasmaPower** [dalek-cryptography/ed25519-dalek#27]
It would be nice to support batch verification of signatures for better performance.

**Comment by isislovecruft** [comment]
Hi @PlasmaPower!

I'd be happy to have batch verification in `ed25519-dalek`, and thanks for making an issue for it.  I can probably get around to it later this week, but if someone else is really excited about working on it please feel free to speak up and claim this issue.

**Comment by isislovecruft** [comment]
There's a WIP in my `feature/27-batch` [branch](https://github.com/isislovecruft/ed25519-dalek/tree/feature/27-batch).

The API could probably be better, and it'll go faster if I (or someone else) implements 128-bit modular arithmetic.
