### ISSUE TITLE
Release a 2.0.0-pre* that upgrades to curve25519-dalek 4.0.0-pre*

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/ed25519-dalek#274]
To eliminate pulling in additional copies of curve especially on memory constrained devices we might want to consider:

1. keeping prereleases in sync with their dependencies' prereleases
2. deprecating dependencies major versions (for less maintenance upkeep)

**Comment by tarcieri** [comment]
I think this is complete?

https://crates.io/crates/ed25519-dalek/2.0.0-pre.0

That said, it'd be great to get another release out now that #285 is merged

**Comment by pinkforest** [comment]
rc.2 Sync coming up:
- https://github.com/dalek-cryptography/curve25519-dalek/pull/522
- https://github.com/dalek-cryptography/ed25519-dalek/pull/295
- x25519 - sending it now
