### ISSUE TITLE
curve25519-dalek version prevents #![no_std] usage.

### ISSUE THREAD

**Issue by LachlanGunn** [dalek-cryptography/ed25519-dalek#29]
This crate currently points to version 0.16.* of `curve25519-dalek`, which does not properly support `no_std` operation due to a build dependency feature issue (fixed in https://github.com/dalek-cryptography/curve25519-dalek/commit/2a1e122300058ed4728bbede2fa9e0f8c4812773#diff-80398c5faae3c069e4e6aa2ed11b28c0) .

The result is that depending on ed25519-dalek with `default-features = false` does *not* result in a `no_std` binary.

Updating this seems to only be a three-line change (and I can confirm that the tests pass on my machine), but before submitting a pull request I would like to make sure that there isn't a good reason to hold `curve25519-dalek` back at 0.16.

**Comment by isislovecruft** [comment]
Hi @LachlanGunn! The latest `develop` branch is using curve25519-dalek 0.18 as of a4be92b. Is that working for you now?

**Comment by isislovecruft** [comment]
Tentatively closing... but if you're still having an issue please feel free to reopen!

**Comment by LachlanGunn** [comment]
Whoops, I should have checked for new commits before opening the issue, as you just beat me to it.

I can confirm that curve25519-dalek from _crates.io_ now works for me without any modifications.
