### ISSUE TITLE
Reintroduce ExpandedSecretKey funcionality

### ISSUE THREAD

**Issue by poljar** [dalek-cryptography/ed25519-dalek#298]
Hi there.

We're using the `dalek` crates in [vodozemac](https://github.com/matrix-org/vodozemac/) as the core for our double ratchet implementation. This is a relatively new library intended to replace our old C based [libolm](https://gitlab.matrix.org/matrix-org/olm/) library.

Now our problem is that libolm always expands Ed25519 secret keys, which are stored long-term.

As we have many users already using libolm, we would like to transfer this expanded Ed25519 key when we transition our users from libolm to vodozemac. We've looked into updating our `ed25519-dalek` dependency, but found that it is no longer possible to construct an `ExpandedSecretKey` as the type is no longer public, as per https://github.com/dalek-cryptography/ed25519-dalek/pull/205.

Is there any way to restore this functionality?

**Comment by tarcieri** [comment]
Per #205, `ExpandedSecretKey` has an unsafe API that was removed to fix a security vulnerability.

It also doesn't conform to any standard interface for Ed25519 keys, such as the one specified in RFC8032.

**Comment by poljar** [comment]
I can definitely see how this API is misuse-prone and aware it isn't a standard interface. We've long considered this behaviour of libolm to be [problematic](https://github.com/matrix-org/olm/issues/53).

Still, it's perfectly possible to use it correctly and our crate packages it up safely, without re-exposing the insecure interface.

Given this is a backward-incompatible change, resulting in a relatively critical loss of functionality preventing us from ever seamlessly migrating, perhaps it could be considered for reintroduction under a feature flag?

Alternatively, many RustCrypto crates offer low level and easy to misuse interfaces under crates or submodules marked as `hazmat`. Maybe even marking the constructor as `unsafe`?

**Comment by tarcieri** [comment]
It's possible, although the @RustCrypto `hazmat` features generally exist as implementation building blocks of higher level constructions, whereas this would be supporting a nonstandard key format which is not allowed under RFC8032 or NIST  SP 800-186.

I would suggest leaving it off the table for a 2.0 release and circling back afterward.

Alternatively, you can maintain a fork. I imagine you'll have to do this for many different libraries for different languages, since it's not a standard API.

**Comment by tarcieri** [comment]
An option that might be more in the spirit of a "hazmat" API would be a low-level signing API which accepts parameterized inputs (i.e. private scalar, derivation input, public key Edwards point, message hash), which could potentially also be used to implement constructions like the various flavors of Ed25519-BIP32

**Comment by poljar** [comment]
It's my understanding that `ExpandedSecretKey` was only insecure due to its `sign_` interface accepting the public key as an argument, rather than the existence of `ExpandedSecretKey` itself being somehow problematic. Rather than outright removing it, couldn't we add `ExpandedSecretKey` back (as suggested by [this comment](https://github.com/dalek-cryptography/ed25519-dalek/pull/205#issuecomment-1279453654)) with a different `sign` interface that doesn't accept the public key but derives it in the implementation? 

> Alternatively, you can maintain a fork. I imagine you'll have to do this for many different libraries for different languages, since it's not a standard API.

Besides libolm itself, which we're trying to sunset, I don't have to maintain any forks. We are using a single library for all our target languages. It would be nice to keep it this way.

**Comment by tarcieri** [comment]
You can always vendor your own `ExpandedSecretKey` into your project

**Comment by rozbb** [comment]
@poljar Trying to determine how much burden this would put on you. Precisely what functionality do you need out of `ExpandedSecretKey`? If it's signing and that's it, then I think it'd be reasonable to keep the old def and vendor the `sign()` function from [here](https://github.com/dalek-cryptography/ed25519-dalek/blob/80aac08c1ca4a4a14912707650413b59c989e79a/src/signing.rs#L769-L787). Are there other things you need?

**Comment by tarcieri** [comment]
@rozbb yeah, that's more or less what I was proposing here, although perhaps even going lower level with it: https://github.com/dalek-cryptography/ed25519-dalek/issues/298#issuecomment-1499432724

Doing that would be a universal solution for everyone who wants to do something nonstandard, so we're not adding one-off nonstandard features every time they come up.

**Comment by poljar** [comment]
> If it's signing and that's it, then I think it'd be reasonable to keep the old def and vendor the sign() function from [here](https://github.com/dalek-cryptography/ed25519-dalek/blob/80aac08c1ca4a4a14912707650413b59c989e79a/src/signing.rs#L769-L787). Are there other things you need?

The things we are using are as follows:

1. `ExpandedSecretKey::from_bytes()`
2. `ExpandedSecretKey::sign()`
3. The `Serialize` and `Deserialize` implementations for `ExpandedSecretKey`.

#299 certainly helps, thanks for that. It still feels a bit weird to have to re-define `ExpandedSecretKey` to have the `from_bytes()` and serialization back, but it isn't too bad.

**Comment by tarcieri** [comment]
Perhaps we could put `ExpandedSecretKey` under `hazmat` and add accessor methods for `scalar` and `nonce` (not wild about the name of the latter, but), so they can be used in conjunction with the low-level signing API.
