### ISSUE TITLE
ed25519 benchmarks never run

### ISSUE THREAD

**Issue by burdges** [dalek-cryptography/ed25519-dalek#316]
I'm maybe doing something stupid, but `cargo bench -p ed25519-dalek` does nothing, and then never run when you simply do `cargo bench` either.

**Comment by rozbb** [comment]
Benches [require](https://github.com/dalek-cryptography/curve25519-dalek/blob/ba737a379071191158bacfa6d138f6249b12fc09/ed25519-dalek/Cargo.toml#L59) `rand_core`. But good point that should be in the README

**Comment by burdges** [comment]
I'm surprised std does not imply rand_core, and yeah a comment somewhere addresses this, but I'll close this issue now I guess.
