### ISSUE TITLE
no_std depends on bincode

### ISSUE THREAD

**Issue by aep** [dalek-cryptography/ed25519-dalek#35]
https://gist.github.com/jamesmunns/8d4de492b1b6eb56f078a1fe975aa758

**Comment by aep** [comment]
cc @jamesmunns

**Comment by jamesmunns** [comment]
Context: We are considering trying to use ed25519 in a microcontroller context.

It looks like the dependency on `bincode` has a hard `std` dependency: https://github.com/TyOverby/bincode/issues/189

**Comment by jamesmunns** [comment]
It also seems to complain about `byteorder`, but from a first glance I can't understand why (you specify no default features):

```
james@archmac13r2 ➜  ed25519-dalek git:(master) cargo build -j1 --no-default-features --target thumbv7em-none-eabihf
   Compiling proc-macro2 v0.4.13
   Compiling typenum v1.10.0                                                                     
   Compiling cc v1.0.18                                                                          
   Compiling unicode-xid v0.1.0                                                                  
   Compiling rand_core v0.2.1                                                                    
   Compiling byteorder v1.2.4                                                                    
   Compiling subtle v0.7.0                                                                       
   Compiling failure_derive v0.1.2                                                               
   Compiling cfg-if v0.1.5                                                                       
   Compiling rustc-demangle v0.1.9                                                               
error[E0463]: can't find crate for `std`                               ] 11/41: byteorder        
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `byteorder`.  
```

**Comment by isislovecruft** [comment]
Hi @aep and @jamesmunns! Thanks for reporting this. It appears to be a bug in [curve25519-dalek](https://github.com/dalek-cryptography/curve25519-dalek), which this crate depends upon. `curve25519-dalek` depends upon `byteorder` for both buildtime and runtime, and I was able to compile [byteorder](https://github.com/BurntSushi/byteorder) with `cargo build -j1 --no-default-features --target thumbv7em-none-eabihf`. I think it may have something to do with `curve25519-dalek`'s two-stage build process where cargo isn't passing either the correct flags or targets to both build stages? (cc/ @hdevalence)

**Comment by isislovecruft** [comment]
Hi @aep and @jamesmunns! We think we've experienced `curve25519-dalek`'s two-stage `build.rs` script causing cross compilation issues elsewhere, and we've made a ticket (https://github.com/dalek-cryptography/curve25519-dalek/issues/217) for replacing it with something friendlier. I'm guessing you're still hitting this issue?

**Comment by aep** [comment]
@isislovecruft thanks. Yeah, still doesn't compile for no-std.

**Comment by tarcieri** [comment]
This is an interesting looking tool for verifying no_std-compatibility https://github.com/hobofan/cargo-nono

**Comment by nickray** [comment]
If you remove thedev-dependencies which aren't no_std-compatible from https://github.com/dalek-cryptography/curve25519-dalek/issues/187, and add `default-features = false` to `rand` here, it's possible to compile for thumb targets.
I'd wager that due to https://github.com/rust-lang/cargo/issues/4866.on mainstream/desktop targets no_std builds aren't actually no_std :)

**Comment by isislovecruft** [comment]
Hi @aep! Are you still hitting issues with no_std? If not, please feel free to reopen this issue (I'm trying to close out old bug reports).

**Comment by aep** [comment]
We don't use rust anymore sorry. Closing sounds good. Don't think many people care about nostd anyway. :)

**Comment by nickray** [comment]
> We don't use rust anymore sorry. Closing sounds good. Don't think many people care about nostd anyway. :)

Hey! :sweat_smile:
