### ISSUE TITLE
Why do I need the full keypair to sign a message?

### ISSUE THREAD

**Issue by bendem** [dalek-cryptography/ed25519-dalek#42]
Is it necessary to have the public key to sign a message?
If that's not the case, why is there a verify method on the public key but not sign method on the secret key?

Most of my code looks like this because of this:
```rs
    let private_key = SecretKey::from_bytes(&private_key).unwrap();
    let public_key = PublicKey::from_secret::<Sha512>(&private_key);
    let keypair = Keypair {
        secret: private_key,
        public: public_key
    };
    keypair.sign(...)
```

**Comment by burdges** [comment]
All your signatures take twice as much CPU time doing that.

**Comment by bendem** [comment]
Right, I should have read the code before asking, yes, the public key is used when signing, that's why there is no `sign` method on `SecretKey`.
https://github.com/dalek-cryptography/ed25519-dalek/blob/5a759ab9fa1671f921777db57394d59be09ce71b/src/ed25519.rs#L589
