### ISSUE TITLE
Cargo build giving errors.

### ISSUE THREAD

**Issue by nimtiazm** [dalek-cryptography/ed25519-dalek#45]
I tried to build the example given at ```https://docs.rs/ed25519-dalek/0.8.1/ed25519_dalek/``` but was unsuccessful. Following are the details:
```rustc 1.31.0-nightly (4699283c5 2018-10-13)```
Cargo.toml (dependencies):
```[dependencies]
ed25519-dalek = { version = "0.8.1", features = ["serde", "nightly"] }
sha2 = "0.8.0"
rand = "0.5.5"```

When I try to simply ```cargo build```, I get the following errors:

```
error[E0277]: the trait bound `sign::sha2::Sha512: digest::Input` is not satisfied           
  --> src/sign.rs:15:28                                                                      
   |                                                                                         
15 |     let keypair: Keypair = Keypair::generate::<Sha512, _>(&mut csprng);                 
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `digest::Input` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
   = note: required by `sign::ed25519_dalek::Keypair::generate`                              
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::BlockInput` is not satisfied      
  --> src/sign.rs:15:28                                                                      
   |                                                                                         
15 |     let keypair: Keypair = Keypair::generate::<Sha512, _>(&mut csprng);                 
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `digest::BlockInput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
   = note: required by `sign::ed25519_dalek::Keypair::generate`                              
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::FixedOutput` is not satisfied     
  --> src/sign.rs:15:28                                                                      
   |                                                                                         
15 |     let keypair: Keypair = Keypair::generate::<Sha512, _>(&mut csprng);                 
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `digest::FixedOutput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
   = note: required by `sign::ed25519_dalek::Keypair::generate`                              
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::Input` is not satisfied           
  --> src/sign.rs:21:40                                                                      
   |                                                                                         
21 |     let signature: Signature = keypair.sign::<Sha512>(message);                         
   |                                        ^^^^ the trait `digest::Input` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::BlockInput` is not satisfied      
  --> src/sign.rs:21:40                                                                      
   |                                                                                         
21 |     let signature: Signature = keypair.sign::<Sha512>(message);                         
   |                                        ^^^^ the trait `digest::BlockInput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::FixedOutput` is not satisfied     
  --> src/sign.rs:21:40                                                                      
   |                                                                                         
21 |     let signature: Signature = keypair.sign::<Sha512>(message);                         
   |                                        ^^^^ the trait `digest::FixedOutput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::Input` is not satisfied           
  --> src/sign.rs:27:13                                                                      
   |                                                                                         
27 |     keypair.verify::<Sha512>(message, &signature).is_ok()                               
   |             ^^^^^^ the trait `digest::Input` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::BlockInput` is not satisfied      
  --> src/sign.rs:27:13                                                                      
   |                                                                                         
27 |     keypair.verify::<Sha512>(message, &signature).is_ok()                               
   |             ^^^^^^ the trait `digest::BlockInput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::FixedOutput` is not satisfied     
  --> src/sign.rs:27:13                                                                      
   |                                                                                         
27 |     keypair.verify::<Sha512>(message, &signature).is_ok()                               
   |             ^^^^^^ the trait `digest::FixedOutput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::Input` is not satisfied           
  --> src/sign.rs:31:12                                                                      
   |                                                                                         
31 |     pubkey.verify::<Sha512>(message, &signature).is_ok()                                
   |            ^^^^^^ the trait `digest::Input` is not implemented for `sign::sha2::Sha512` 
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::BlockInput` is not satisfied      
  --> src/sign.rs:31:12                                                                      
   |                                                                                         
31 |     pubkey.verify::<Sha512>(message, &signature).is_ok()                                
   |            ^^^^^^ the trait `digest::BlockInput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error[E0277]: the trait bound `sign::sha2::Sha512: digest::FixedOutput` is not satisfied     
  --> src/sign.rs:31:12                                                                      
   |                                                                                         
31 |     pubkey.verify::<Sha512>(message, &signature).is_ok()                                
   |            ^^^^^^ the trait `digest::FixedOutput` is not implemented for `sign::sha2::Sha512`
   |                                                                                         
   = note: required because of the requirements on the impl of `digest::digest::Digest` for `sign::sha2::Sha512`
                                                                                             
error: aborting due to 12 previous errors                                                    
                                                                                             
For more information about this error, try `rustc --explain E0277`.                                                                              
```

**Comment by webmaster128** [comment]
Downgrading sha2 to `sha2 = "0.7"` is a workaround for me. Probably related to https://github.com/dalek-cryptography/ed25519-dalek/issues/46

**Comment by isislovecruft** [comment]
Hi @nimtiazm! Sorry I missed this, but it looks like you sorted out the dependency mismatch? Closing but feel free to reopen if you have more issues.

**Comment by fadedbee** [comment]
I had to downgrade to sha2 = "0.8", "0.7" resulted in:
```

error[E0277]: the trait bound `sha2::sha512::Sha512: digest::Input` is not satisfied
    --> src/bin/benchmark.rs:37:29
     |
37   |     let keypair: ed::Keypair = ed::Keypair::generate::<Sha512, _>(&mut csprng);
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `digest::Input` is not implemented for `sha2::sha512::Sha512`
     | 
    ::: /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-0.9.1/src/ed25519.rs:1145:18
     |
1145 |         where D: Digest<OutputSize = U64> + Default,
     |                  ------------------------ required by this bound in `ed25519_dalek::ed25519::Keypair::generate`
     |
help: trait impl with same name found
    --> /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/sha2-0.7.1/src/sha512.rs:88:1
     |
88   | / impl digest::Input for Sha512 {
89   | |     fn process(&mut self, msg: &[u8]) { self.engine.input(msg); }
90   | | }
     | |_^
     = note: perhaps two different versions of crate `digest` are being used?
     = note: required because of the requirements on the impl of `digest::digest::Digest` for `sha2::sha512::Sha512`

error[E0277]: the trait bound `sha2::sha512::Sha512: digest::FixedOutput` is not satisfied
    --> src/bin/benchmark.rs:37:29
     |
37   |     let keypair: ed::Keypair = ed::Keypair::generate::<Sha512, _>(&mut csprng);
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `digest::FixedOutput` is not implemented for `sha2::sha512::Sha512`
     | 
    ::: /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-0.9.1/src/ed25519.rs:1145:18
     |
1145 |         where D: Digest<OutputSize = U64> + Default,
     |                  ------------------------ required by this bound in `ed25519_dalek::ed25519::Keypair::generate`
     |
help: trait impl with same name found
    --> /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/sha2-0.7.1/src/sha512.rs:92:1
     |
92   | / impl digest::FixedOutput for Sha512 {
93   | |     type OutputSize = U64;
94   | |
95   | |     fn fixed_result(mut self) -> GenericArray<u8, Self::OutputSize> {
...    |
101  | |     }
102  | | }
     | |_^
     = note: perhaps two different versions of crate `digest` are being used?
     = note: required because of the requirements on the impl of `digest::digest::Digest` for `sha2::sha512::Sha512`

error[E0277]: the trait bound `sha2::sha512::Sha512: digest::Reset` is not satisfied
    --> src/bin/benchmark.rs:37:29
     |
37   |     let keypair: ed::Keypair = ed::Keypair::generate::<Sha512, _>(&mut csprng);
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `digest::Reset` is not implemented for `sha2::sha512::Sha512`
     | 
    ::: /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-dalek-0.9.1/src/ed25519.rs:1145:18
     |
1145 |         where D: Digest<OutputSize = U64> + Default,
     |                  ------------------------ required by this bound in `ed25519_dalek::ed25519::Keypair::generate`
     |
     = note: required because of the requirements on the impl of `digest::digest::Digest` for `sha2::sha512::Sha512`

error: aborting due to 3 previous errors; 13 warnings emitted

For more information about this error, try `rustc --explain E0277`.
```

**Comment by tarcieri** [comment]
These are extremely outdated versions of all of the crates involved. The latest version of ed25519-dalek is v1.0.0-pre.4
