### ISSUE TITLE
Update to digest 0.8 and sha2 0.8

### ISSUE THREAD

**Issue by tarcieri** [dalek-cryptography/ed25519-dalek#46]
There are new versions of these crates out with a pretty big `generic-array` bump (0.12), which will also be the first version of `generic-array` to be packaged by some Linux distributions.

This is presently blocked on https://github.com/dalek-cryptography/curve25519-dalek/pull/201

**Comment by tarcieri** [comment]
In the curve25519-dalek PR, I'm trying to have it do `pub extern crate digest`:

https://github.com/dalek-cryptography/curve25519-dalek/pull/201/files#r221957818

In which I would suggest ed25519-dalek do the following in the crate root:

```
pub use curve25519_dalek::digest;
```

...which means that crates that depend on ed25519-dalek and otherwise don't care about the digest version can do:

```
use ed25519_dalek::digest;
```

**Comment by isislovecruft** [comment]
Hi @tarcieri! Thanks for the reminder. This was fixed in https://github.com/dalek-cryptography/ed25519-dalek/commit/b97fa08900c2ac01f3555ffe58eb184f80c2bf78
