### ISSUE TITLE
Change internals of `PublicKey` to store both compressed Edwards Y and decompressed point forms

### ISSUE THREAD

**Issue by isislovecruft** [dalek-cryptography/ed25519-dalek#61]
Since the type is currently `#[repr(C)]` this will cause issues for anyone who was passing it over an FFI boundary directly (i.e. without first using the serde serialisation or calling `to_bytes()`, etc.). However, this will give us a speedup on non-batch verification as it avoids the point decompression.

**Comment by hdevalence** [comment]
It might be good to remove the `#[repr(C)]` and provide byte-oriented functions for FFI, so that the Rust types aren't encumbered by FFI considerations at all and can maintain whatever invariants they want.

**Comment by isislovecruft** [comment]
This was implemented in #62 and will be available in `1.0.0-pre.1`. It gives roughly a 35% speed up on key reuse for signature verification (batch or otherwise).
