### ISSUE TITLE
remove failure

### ISSUE THREAD

**Issue by aep** [dalek-cryptography/ed25519-dalek#67]
failure doesn't work on mips because it depends on backtrace.
It looks trivial to remove, and i would just open a PR, but i'm not sure what the original intend of adding it was. Is this something that should be behind a feature flag?

**Comment by tarcieri** [comment]
This crate uses `failure` with `default-features = false` and therefore you shouldn't be encountering any issues related to the `backtrace` crate. Can you post what error you're encountering?

**Comment by aep** [comment]
interesting. the other crate turns out to only have a build dependency to failure. 
i wonder if that confuses cargo. will dig deeper, thanks

**Comment by tarcieri** [comment]
Yes, it's a known deficiency of cargo (it does not support separate dependency resolution for dev/build). See:

https://github.com/rust-lang/cargo/issues/4664
https://github.com/rust-lang/cargo/issues/4866

**Comment by aep** [comment]
Darn. will remove the other thing then to see if that makes it all work. thanks!
