### ISSUE TITLE
Upgrade to Rust 2018 ?

### ISSUE THREAD

**Issue by sunhuachuang** [dalek-cryptography/ed25519-dalek#74]
I think it will be better if curve25519 and x25519 upgrade together

**Comment by LuoZijun** [comment]
I think this issue is outdated.

CodeLine:
https://github.com/dalek-cryptography/ed25519-dalek/blob/3ffa9ff530750f590645e3886c40c2184c04a963/Cargo.toml#L4

**Comment by sunhuachuang** [comment]
closed.
