### ISSUE TITLE
Custom-digest use broken?

### ISSUE THREAD

**Issue by dpc** [dalek-cryptography/ed25519-dalek#75]
Creating a new issue for this, as it might be important. https://github.com/dalek-cryptography/ed25519-dalek/issues/69#issuecomment-470250044

**Comment by isislovecruft** [comment]
This is [on purpose](https://github.com/dalek-cryptography/ed25519-dalek/issues/69#issuecomment-470250044).

**Comment by dpc** [comment]
This looks weird to me. What's even the point of generalizing over `D: Digest` if nothing is using it. https://docs.rs/ed25519-dalek/1.0.0-pre.1/src/ed25519_dalek/public.rs.html#212-246
