### ISSUE TITLE
ECDH implementation

### ISSUE THREAD

**Issue by elichai** [dalek-cryptography/ed25519-dalek#81]
Hi,
I can't seem to find a way to easily make a generate a ECDH key here.
am I missing something or is that not implemented?

(I'm looking for something similar to: https://gitweb.torproject.org/tor.git/tree/src/lib/crypt_ops/crypto_curve25519.c#n268)

Thanks!

**Comment by tarcieri** [comment]
You are probably looking for https://github.com/dalek-cryptography/x25519-dalek

**Comment by elichai** [comment]
Looks interesting, although that involves generating a random number and not using a priv+pub pair, maybe this is what I need? https://docs.rs/x25519-dalek/0.5.2/x25519_dalek/fn.x25519.html

**Comment by elichai** [comment]
@tarcieri What I need is a way to convert `[u8;32]` / `SecretKey` to EphemeralSecret

**Comment by tarcieri** [comment]
If you really want to do static D-H, the raw X25519 function you linked to seems fine for that purpose

**Comment by isislovecruft** [comment]
I wouldn't personally recommend reusing an ed25519 secret key as an x25519 secret, as static diffie-hellman (i.e. not using ephemeral keys) is less than ideal. However if you need to do this for some reason, the `x25519` function you linked to is the correct way.
