### ISSUE TITLE
Example with u64

### ISSUE THREAD

**Issue by pakipaki2000** [dalek-cryptography/ed25519-dalek#83]
Hi,

i'd really like to use the official functions:

  ```
                      let pub: ed25519::public_key = ed25519::public_key::from_bytes(U64;4 HERE).unwrap();
                        let sig: ed25519::signature = ed25519::signature::from_bytes(U64;8).unwrap();
```
                        
Would be awesome if you can show me a working example on how to do it :)

Thanks!

**Comment by tarcieri** [comment]
Why?

**Comment by pakipaki2000** [comment]
All the code is in u64;4 - u64;8 already

**Comment by isislovecruft** [comment]
Hi, I'm not sure what you mean by "official"? How are you getting these `u64`s? Can you not just use `std::mem::transmute` to turn them into `u8`s?

**Comment by james-darkfox** [comment]
And `to_le()` on each u64.
