### ISSUE TITLE
Signature Error, how to avoid panic!

### ISSUE THREAD

**Issue by HandleMaser** [dalek-cryptography/ed25519-dalek#84]
Hello,

I'm getting SignatureError(PointDecompressionError) when users send me wrong data and it crash my whole program (Actix). How can I use verify_prehashed without making it crash?

<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SignatureError(PointDecompressionError)', src/libcore/result.rs:997:5

**Comment by james-darkfox** [comment]
Are you doing `verify(..).unwrap()`? If so, stop doing `.unwrap()`. That is your assertion failing.

**Comment by HandleMaser** [comment]
Thanks, the problem was actually on the to_bytes() from the PublicKey not the verification itself.
