### ISSUE TITLE
Public Key / Signature as Hex

### ISSUE THREAD

**Issue by NN-Binary** [dalek-cryptography/ed25519-dalek#85]
Hi,

i'm trying to send Public keys & Signatures over a chat, but I'm having a very hard time converting it to Hex (as a string).

println!("PUBLIC KEY {:x}", public_key);
    |                                     ^^^^^^^^^^ the trait `std::fmt::LowerHex` is not implemented for `ed25519::PublicKey

can anyone provide me a working example to generate a pubkey/convert it to hex string (and signature)

Thank you so much

**Comment by hdevalence** [comment]
Try using [`hex::encode`](https://docs.rs/hex/0.3.2/hex/fn.encode.html) on the bytes of the public key?

**Comment by james-darkfox** [comment]
@hdevalence That is the answer they got on their [Reddit thread](https://www.reddit.com/r/rust/comments/bofj06/ed25519dalek_as_hex/). Resolved but not closed here.

**Comment by tarcieri** [comment]
If you or anyone else is interested in serializing the keypair (which includes the secret key/scalar) as hex, consider [`subtle_encoding::hex`](https://docs.rs/subtle-encoding/latest/subtle_encoding/hex/index.html) which provides constant-time serialization (also for [base64](https://docs.rs/subtle-encoding/0.3.4/subtle_encoding/base64/index.html)).
